### ISSUE TITLE
Support for - (CGSize)collectionView:layout:sizeForItemAtIndexPath:

### ISSUE THREAD

**Issue by peterpaulis** [jwilling/JNWCollectionView#120]
Can it be possible to add support for

- (CGSize)collectionView:(UICollectionView *)collectionView layout:(UICollectionViewLayout *)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath *)indexPath 

so that cells may have different size, based on their indexPath?

**Comment by jwilling** [comment]
I'm going to close this in favor of issue #103.
