### ISSUE TITLE
datasource methods not called, even though datasource is set

### ISSUE THREAD

**Issue by jhoughjr** [jwilling/JNWCollectionView#127]
I set the datasource and the delegate in my storyboard, as well as in viewDidLoad after my first attempts failed. A breakpoint in `- (JNWCollectionViewCell *)collectionView:(JNWCollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath` is never reached after calling reloadData.

`- (NSUInteger)collectionView:(JNWCollectionView *)collectionView numberOfItemsInSection:(NSInteger)section` is reached however.

From what I recall about tableview in iOS both should be called after a reloadData unless numberOfItems returns zero.

I've spent about an hour 
Hopefully I'm just missing something, since this control will save me some time.

Heres output verifying the datasource and delegate are set

```
(lldb) po [[[[[self.view subviews] lastObject] subviews] firstObject] delegate]
<XXXViewController: 0x6000000e2e00>

(lldb) po [[[[[self.view subviews] lastObject] subviews] firstObject] dataSource]
<XXXViewController: 0x6000000e5980>

(lldb) 
(lldb) po [[[[self.view subviews] lastObject] subviews] firstObject]
<JNWCollectionView: 0x1041076c0; frame = {{0, 0}, {479, 353}}; layer = <_NSViewBackingLayer: 0x610000044380>; content offset: {0, 0}> collection view layout: <JNWCollectionViewGridLayout: 0x6080000c3d40>
```

here is my setup code mostly copied from the readme.

```
- (void)setupCollectionView {
    JNWCollectionViewGridLayout *gridLayout = [[JNWCollectionViewGridLayout alloc] init];

    // The grid layout has its own delegate, so if we want to implement the delegate methods
    // we need to conform to JNWCollectionViewGridLayoutDelegate.

    // Tell the grid layout the size of our cells.
    gridLayout.itemSize = CGSizeMake(100, 100);
    self.view.memeCollectionView.dataSource = self;
    self.view.memeCollectionView.delegate = self;
    // Set the grid layout as the collection view layout, or the layout
    // that is used for positioning the items in the collection view.
    self.view.memeCollectionView.collectionViewLayout = gridLayout;
    [self.view.memeCollectionView registerClass:[JNWCollectionViewCell class]
                     forCellWithReuseIdentifier:@"MMMCell"];
}
```

**Comment by Utkarshagupta** [comment]
I am having the same issue, please help me out with the configuration you missed.

**Comment by EpicDraws** [comment]
I'm also having this issue--was anyone able to figure out what the fix was?

**Comment by jwilling** [comment]
@EpicDraws How does your setup differ from what's shown in the demo app? Are you aware of the lifetime of the object that you're setting as the data source?

**Comment by EpicDraws** [comment]
Turns out I needed to have the view be a scroll view and not an NSView. It also seems you have to create the cell in code and not in IB.

**Comment by jwilling** [comment]
Yes, `JNWCollectionView` inherits from a scroll view, so you should set it up as one. You should be able to use a separate nib for the cell though, as support exists for that functionality.

**Comment by wowthatisrandom** [comment]
@jwilling i work w @EpicDraws and am having trouble getting the separate cell nib to show subviews. I was able to get it working programmatically using your demo code but not with interface builder.

I created a NSView in interface builder set the class to `JNWCollectionViewCell` and the cell an identifier. I then connected the objects to the cell's subclass. I then registered the nib in the 
` [hourlyTimelineCollectionView registerClass:HourlyTimelineCell.class forCellWithReuseIdentifier:@"hourlyTimelineCell"];`

and finally i set the NSTextFields in `- (JNWCollectionViewCell *)collectionView:(JNWCollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath` using `        cell.condition.stringValue = conditions[index];
` However nothing is set (NSTextField doesnt show at all). Any help would be greatly appreciated. Thanks

**Comment by jwilling** [comment]
You need to use the proper method for registering the cells. Instead of using `registerClass:forCellWithReuseIdentifier`, use `registerNib:forCellWithReuseIdentifier:`.

I made a sample project for you that uses nib cells. You can grab it [here](https://www.dropbox.com/s/zyk8ibjnuoaljdy/nib-sample.zip).

**Comment by wowthatisrandom** [comment]
@jwilling thats embarrassing. Always the simple things. fixed it instantly thanks so much for the help.
