### ISSUE TITLE
Multiple Selections

### ISSUE THREAD

**Issue by jcampbell05** [jwilling/JNWCollectionView#138]
Can I enable multiple selections via the mouse or keyboard modifier ?

**Comment by jwilling** [comment]
This response is probably too late, sorry, but yes this is supported. Just use the standard OS X keyboard modifiers. Shift clicking an item will extend a contiguous selection, and holding command provides multiple selection.

**Comment by danwexler** [comment]
Shift-arrow is not calling the "ModifySelection" JNWCollectionView methods for me. Is this working for others?

**Comment by danwexler** [comment]
I found a fix. In my derived JNWCollectionView, I had to override keyDown:

    // Override this NSResponder method to force shift+arrow to call *AndModifySelection
    - (void)keyDown:(NSEvent *)theEvent {
        [self interpretKeyEvents:@[theEvent]];
    }

**Comment by jwilling** [comment]
@danwexler Interestingly enough, that's how it was originally implemented. I was instructed that it wasn't the correct approach. See #60. Odd.

**Comment by danwexler** [comment]
Fascinating. Without keyDown, they are not called for me. Any clue why the fooModifySelection methods are not being called for me or what I need to do to get them called properly?

**Comment by jwilling** [comment]
Was able to verify that behavior today. You're correct that without interpreting the key events it doesn't actually seem to handle modifying selections. Not sure why it seems to be working for some people and not others. Wonder if it has to do with the way that their responder chain is set up?
