### ISSUE TITLE
JNWCollectionView Data source not called

### ISSUE THREAD

**Issue by Utkarshagupta** [jwilling/JNWCollectionView#140]
I am new to OSx development . Please help me out 
I cloned the project to my local machine but when running the APP below data source method is not called.

- (JNWCollectionViewCell *)collectionView:(JNWCollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath

![screen shot 2015-05-14 at 4 48 38 pm](https://cloud.githubusercontent.com/assets/10269638/7630927/2b7aadfe-fa59-11e4-8b24-a8a8f03aa0e3.png)

**Comment by jwilling** [comment]
I see you're running the demo app. Have you made any modifications to it? It should work fine as it is.

**Comment by Utkarshagupta** [comment]
No i have not made any modifications to it

**Comment by jwilling** [comment]
What OS and Xcode version are you on? How did you clone the project? Make sure you include all of the dependencies.

    git clone --recursive https://github.com/jwilling/JNWCollectionView.git

**Comment by jwilling** [comment]
If you're still having this problem, please let me know. Otherwise, I'm going to assume this has been resolved.

**Comment by Utkarshagupta** [comment]
Thanks a lot for the help :) You can resolve it.
