### ISSUE TITLE
Why is JNWCollectionView tag readonly

### ISSUE THREAD

**Issue by KCastiglione** [jwilling/JNWCollectionView#141]
The 'tag' property of JNWCollectionView is readonly and can't be changed.
It will be great if it can be writeable, as it can be used to differentiate between the different JNWCollectionView in delegates such as cellForItemAtIndexPath etc.

Alternatively is there a different property that can be used for this?

![screen shot 2015-05-31 at 2 54 44 pm](https://cloud.githubusercontent.com/assets/96905/7904108/feb670ec-07a4-11e5-8778-dc8d134bdb76.png)

Thanks again for a great library.

**Comment by jwilling** [comment]
That's a property on `NSView`, not my collection view. It's readonly. The delegate methods send a reference to the collection view that sent the message. You should be able to use that reference to see which collection view you're dealing with.

https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSView_Class/#//apple_ref/occ/instp/NSView/tag

**Comment by KCastiglione** [comment]
I have two JNWCollectionViews and they both have the same delegate for data source. How can I differentiate or find out which collection view is sending the message to delegate?

In iOS UICollectionViews I do something like this

    - (JNWCollectionViewCell *)collectionView:(JNWCollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath {
           if (collectionView.tag==kChatCollectionViewTag) {
                  //prepare cell for chat collection view 
           } else {
                  //prepare cell for other collection view 
           }


How can I accomplish the same with JNWCollectionView
Thanks once again for a great library!

**Comment by jwilling** [comment]
Just compare the pointers? You should keep a reference to each of the two collection views.

``` objc
- (JNWCollectionViewCell *)collectionView:(JNWCollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath {
       if (collectionView == self.chatCollectionView) {
              // prepare cell for chat collection view 
       } else { // self.otherCollectionView
              // prepare cell for other collection view 
       }
}
```

**Comment by KCastiglione** [comment]
That worked yeah! thanks again for an awesome library and all the help!
