### ISSUE TITLE
ability to hide empty section

### ISSUE THREAD

**Issue by pvinis** [jwilling/JNWCollectionView#144]
is there a way to do that? if i have 3 sections, and the second section is empty, can i hide the header?

**Comment by jwilling** [comment]
Which layout are you using? Assuming you're using the grid layout, you should be able to return a height of 0 for empty sections in the delegate method called from the grid layout delegate (`-collectionView:heightForHeaderInSection:`).

**Comment by pvinis** [comment]
true. thank you.

**Comment by markmark1** [comment]
Love the jnwcollectionview

**Comment by jwilling** [comment]
@markmark1 Thanks, glad to hear it!
