### ISSUE TITLE
Drag n Drop image 

### ISSUE THREAD

**Issue by inceptiveKshitij** [jwilling/JNWCollectionView#145]
Hi, this code is so nice to understand. But I have problem. I want to Drag images from gridview n drop on desktop. What should I do for that in this code.

**Comment by jwilling** [comment]
Sorry for the delay. Unfortunately this is not supported in my version of JNWCollectionView. There is a pull request that supports drag and drop, so feel free to check it out. https://github.com/jwilling/JNWCollectionView/pull/59
