### ISSUE TITLE
CollectionView asks for cells (list layout only) when section.numberOfRows is 0.

### ISSUE THREAD

**Issue by JeffreyFrey** [jwilling/JNWCollectionView#146]
JNW provided fix (Thank you again Jonathan)

 if (section.numberOfRows > 0 && CGRectIntersectsRect(section.frame, rect)) .....

**Comment by Shebuka** [comment]
I've got same problem and fixed it with:

    if (CGRectGetHeight(section.frame) == 0)
        continue;

but I think Jonathans solution is better.

BTW: it's in JNWCollectionViewListLayout.m row 199.
