### ISSUE TITLE
Pull to load more rows

### ISSUE THREAD

**Issue by Shebuka** [jwilling/JNWCollectionView#147]
Hi,
I'm trying to implement the pull to load, or at least sort off.
My previous implementation was by observing `NSViewBoundsDidChangeNotification` and set the `scrollPoint` to the origin of the old row 0, but with `JNWCollectionView` it's not working well when you fast scroll to top.
Do you have any advice on how to do it in clear way?

Thank you,
Shebuka

**Comment by jwilling** [comment]
Without subclassing both the clip view and the scroll view I'm not sure how clean you could make it. It's potentially possible to implement this by adding a helper that listens to the bounds changed notifications and adjusts the content insets of the scroll view dynamically, as needed. I haven't tried something like this so I can't say for certain what issues you'd run into, but that's would be my first approach.

**Comment by jwilling** [comment]
If you need more help please feel free to reopen this. I'm closing it for now. Thanks!
