### ISSUE TITLE
Add an objectValue property to the JNWCollectionViewCell

### ISSUE THREAD

**Issue by konstantinpavlikhin** [jwilling/JNWCollectionView#149]
I use a `JNWCollectionView` a lot and nearly every time I want my cells to represent some particular model objects.

A modern view-based `NSTableView` cells has an `objectValue` property that is set to an object that is returned from a data source method `- (nullable id)tableView:(NSTableView *)tableView objectValueForTableColumn:(nullable NSTableColumn *)tableColumn row:(NSInteger)row;`. Starting from OS X 10.11 `NSTableView` also does an important thing of [setting this property to nil when cells go to the reuse queue](https://developer.apple.com/library/mac/releasenotes/AppKit/RN-AppKit/#10_11TableView).

Its common for Cocoa applications to utilize bindings. When you have an `objectValue` property on your cell you can easily bind properties of a nested subviews to it.

I believe `JNWCollectionView` would benefit from this.

**Comment by jwilling** [comment]
This API sounds like it could potentially be useful. Pull requests are welcome!

**Comment by Deadpikle** [comment]
@jwilling Should this issue be closed per the pull request I did ( #179 )? Was just looking at the issue list and noticed it.

**Comment by jwilling** [comment]
@Deadpikle Good call, thanks!
