### ISSUE TITLE
Expand a View Cell

### ISSUE THREAD

**Issue by joelongstreet** [jwilling/JNWCollectionView#154]
I've implemented a basic JNWCollectionView and it works great! I'm working on a new feature which allows a user to click on a cell and expand it.

Is there any other method I can call besides `reloadData` which will redraw the cells in the collection view? Looks like `reloadData` rebuilds each collection view item. I'd like to store a "height" property in a subclassed collection view item and implement the heightForRowAtIndexPath like this:

    - (CGFloat)collectionView:(JNWCollectionView *)collectionView heightForRowAtIndexPath:(NSIndexPath *)indexPath{
        TimeEntryViewController *cell = (id)[collectionView dequeueReusableCellWithIdentifier:@"id"];
        return [cell height];
    }

Let me know if I'm approaching this wrong or if there's an easier way to implement.

**Comment by jwilling** [comment]
Hello! Sorry for the delay in responding to you.

Although I haven't tried this out in all scenarios, it should be possible to just call `invalidateLayout` on your collection view layout. It should redraw the cells and re-query the delegate for the correct cell height. Let me know if that works for you!

**Comment by joelongstreet** [comment]
Thanks, calling `invalidateLayout` rebuilds the view controllers. I was initially wanting to store the height in the view controller, but was able to put it in the model with a little more work.
