### ISSUE TITLE
Single row, horizontal scroll.

### ISSUE THREAD

**Issue by whydna** [jwilling/JNWCollectionView#158]
Seems simple/common thing, but I could not figure out how to do it.

Basically, I want to lay out cells from left to right, with horizontal scrolling. Only 1 row. 

what is the best way to achieve this?

**Comment by jwilling** [comment]
You'll want to create a custom layout (or subclass one of the layouts) override the - `scrollDirection` method to return `JNWCollectionViewScrollDirectionHorizontal`.Then make sure the content size is such that the content height is the bounds of the collection view, and the content width is as wide as you want it to be. That should do the trick.
