### ISSUE TITLE
Cells are reinitialized on layout for window size changes

### ISSUE THREAD

**Issue by rharter** [jwilling/JNWCollectionView#161]
On layout, all currently visible cells are removed from the `visibleCellsMap` and enqueued, then refetched with `[self.dataSource collectionView:self cellForItemAtIndexPath:indexPath]` regardless of whether they will, in fact, still be visible as a result of the layout.  This seems quite inefficient, as resizing the window will cause all visible cells to be recycled and refetched on each draw cycle.

In my particular scenario, this is problematic because I'm trying to show a stack of photos in each cell, with the photos behind the front each drawn at a random slight angle, so they look like a stack.  I generate the random angles when the cell is set up, but that happens on each frame when the window is being resized, making the photos look like they're wiggling. 

I've been out of Cocoa dev for a while, so I may be missing something, but it seems like we aught to be able to check if the cell will still be visible after the layout cycle in `JNWCollectionViewFramework.m:layoutCellsWithRedraw:BOOL` and simply apply the updated layout attributes, if so, otherwise recycle it and get a new one for that position.  Is there something I'm missing?

**Comment by rharter** [comment]
This seems to simply be an issue with the Grid layout.

**Comment by Deadpikle** [comment]
Have you looked at https://github.com/jwilling/JNWCollectionView/issues/117 ?

**Comment by rharter** [comment]
You're right @Deadpikle, I'll close this as a dupe of #117.
