### ISSUE TITLE
Background Color 

### ISSUE THREAD

**Issue by Ravichandrane** [jwilling/JNWCollectionView#177]
Hey ! 

I'm wondering how can I change the background color of JNWCollectionView ? 
I set drawsBackground to true but nothing happened... 

Thanks,
Cheers.

**Comment by jwilling** [comment]
The `drawsBackground` property defaults to true. Just set a color on the `backgroundColor` property and it should work.

For example:
   collectionView.backgroundColor = NSColor.redColor;
