### ISSUE TITLE
control + Click doesn't spawn context menu

### ISSUE THREAD

**Issue by gietal** [jwilling/JNWCollectionView#186]
I tried playing around on the demo by adding menu item to the cells, but it seems like the context menu is only respected for right click, not control+click

is this by design that the app should handle this manually? or am I missing something important?

**Comment by jwilling** [comment]
I seem to recall there being some oddities with `-menuForEvent:` and subviews. See [here](http://sound-of-silence.com/?article=20150923). It's left to be implemented manually if that is important, as there's no clean way to do it as far as I'm aware.

On a side note, if you're just starting a new project I'd recommend using the new `NSCollectionView`, unless you're needing to support 10.9 or 10.10.

**Comment by gietal** [comment]
thanks for your reply!

yes I do need to support 10.10 on my app
